name: build-and-push
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: build static assets here if you use a bundler
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - run: npm ci
      # - run: npm run build

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        env:
          IMAGE: ghcr.io/puttrix/puttski.com
        run: |
          docker build -t $IMAGE:latest .
      
      - name: Push image
        env:
          IMAGE: ghcr.io/puttrix/puttski.com
        run: |
          docker push $IMAGE:latest